### ISSUE TITLE
CI: Publish canary plugin builds

### ISSUE THREAD

**Issue by vdice** [fermyon/spin-python-sdk#30]
Publish canary builds of the py2wasm plugin on each merge to main, in the form of a GitHub release (should be a 'pre-release').

The plugin manifest can be co-located on the same GH release.  Ideally, the plugin manifest is auto-generated in the same CI workflow.

Users/automation can then install the canary version via `spin plugins install -u <url to the manifest>`

**Comment by dicej** [comment]
I think this needs a bit more work, since the canary artifacts don't currently have manifests and thus can't be installed using `spin plugin install`.  We'll need something like https://github.com/fermyon/spin-js-sdk/blob/91a01826b26588fa35431b111b031d08e860519e/.github/workflows/release.yaml#L238-L240, I believe.
